### ISSUE TITLE
How to draw table in cheatsheets

### ISSUE THREAD

**Issue by lengyijun** [cheat/cheatsheets#36]
```
Rust         | Cpp              |                      
=============|==================|=====================|=======================
a:&T         | const T* const a | 都不能修改          | 不可变引用的不可变绑定
mut a:&T     | const T* a       | 不能修改a指向的内容 | 不可变引用的可变绑定
a:&mut T     | T* const a       | 不能修改a           | 可变引用的不可变绑定
mut a:&mut T | T*a              | 都能修改            | 可变引用的可变绑定

```

Currently, I draw table like this. Is there any way to make more complex table?

**Comment by chrisallenlane** [comment]
What you're doing there is probably the best solution. I'm not personally aware of a better solution for drawing ASCII tables.

As an aside, though - it looks like you're using `cheat` to (sort of) manage code snippets. I've been pretty actively working on a `cheat` plugin for `vim` that (IMO) works _really_ well for this. If you're a `vim` user, keep your eyes open for that release :slightly_smiling_face:
