### ISSUE TITLE
git push tag to remote

### ISSUE THREAD

**Issue by manfredlotz** [cheat/cheatsheets#7]
I would like to have added how to push a tag to remote:

`git push origin <tagname>`

**Comment by Jonny-exe** [comment]
Added it to the git cheatsheet

**Comment by manfredlotz** [comment]
Thx. Could it be you have a typo? 

When I run `cheat git` I see:

```
# push a tag to remove
git push origin v2.1.0_2020-04-12
```
remove instead of remote

**Comment by Jonny-exe** [comment]
Yes, didn't realize.  Thanks

**Comment by chrisallenlane** [comment]
Closing as resolved with #48.
