### ISSUE TITLE
Tags syntax

### ISSUE THREAD

**Issue by bgrundy** [cheat/cheatsheets#72]
The syntax for `tags` is incorrect for many files.  `tags` should be followed by a colon (`:`) in order to work with the `-t` option.  For example, look at the tag lines for files tagged with `networking`.  

    dhclient:tags: [ networking ]
    ip:tags [ networking ]
    iptables:tags [ networking ]
    iwconfig:tags [ networking ]
    nc:tags [ networking ]
    ncat:tags [ networking ]
    netstat:tags [ networking ]
    nmap:tags [ networking ]
    nmcli:tags [ networking ]
    ping:tags [ networking ]
    ping6:tags [ networking ]
    route:tags [ networking ]
    socat:tags [ networking ]
    sockstat:tags [ networking ]
    ss:tags [ networking ]

Only the tag for `dhclient` is picked up with the `-t` option (note the colon after `tags:` for `dhclient` in the output above).

    $ cheat -l -t networking
    title:        file:                                                    tags:
    dhclient ./cheatsheets/community/dhclient      community,networking

**Comment by bgrundy** [comment]
I submitted a pull request for the fix, for what it's worth.  My first, so if I did it wrong, be gentle...

**Comment by chrisallenlane** [comment]
Thanks for this ticket, and especially thanks for the PR to resolve the problem. I just merged that into `master`.

This was an embarrassing mistake. I've been working on improving our build pipeline recently, and in the near-term, I plan to write a lightweight linter for cheatsheets that will help us catch similar errors going forward.

Thanks!
